defaultPicUrl: http://ironsummitmedia.github.io/startbootstrap-clean-blog/img/home-bg.jpg
paginate: 8
paginate_path: "page:num"
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
